name: Test (Linux)

on:
  [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: libMVRGdtf - checkout repository
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf

      - name: Build
        uses: ./libMvrGdtf/.github/actions/build-lib

      - name: Testing...
        working-directory: libMvrGdtf/build
        run: |
          ./MvrGdtfUnitTest
