name: Build OS
description: Build for the current OS
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: "https://npm.pkg.github.com"
        scope: "@mvrdevelopment"

    - name: Build Linux
      if: runner.os == 'Linux'
      uses: ./libMvrGdtf/.github/actions/build-ubuntu
      
    - name: Build Windows
      if: runner.os == 'Windows'
      uses: ./libMvrGdtf/.github/actions/build-windows
      
    - name: Build macOS
      if: runner.os == 'macOS'
      uses: ./libMvrGdtf/.github/actions/build-macos
