name: Release on NPM

on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under ./libMvrGdtf
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
          fetch-depth: 0
          submodules: true
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@mvrdevelopment'
      - uses: mymindstorm/setup-emsdk@v14
      - name: Install prerequisites
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y cmake
          sudo apt-get install uuid-dev
      # libMVRGdtf expects XMLChar be uint16_t
      - name: Xerces-C - build
        shell: bash
        working-directory: libMvrGdtf/xerces-c
        run: |
          emconfigure ./configure --disable-shared --enable-xmlch-uint16_t --prefix=$(pwd)/_build CFLAGS="-fPIC" CXXFLAGS="-fPIC" 
          make -j
          make install

      - name: libMVRGdtf - build
        shell: bash
        working-directory: libMvrGdtf/libMVRgdtf
        run: |
          mkdir build
          cd build
          emmake cmake .. -DUNITTEST=FALSE -DEXTRA_LIBS="curl;icuuc;icudata;icui18n;icuio" -DXERCES_LIB_PATH="$(pwd)/../../xerces-c/_build/lib/libxerces-c.a" -DBUILD_MVR_XCHANGE=false
          make -j
      - name: Prepare package
        shell: bash
        working-directory: libMvrGdtf/libMVRgdtf
        run: |
          mkdir -p output/include
          cp -r src/Include/* output/include/

          mkdir -p output/lib
          cp ../xerces-c/_build/lib/libxerces-c.a ./libs/libxerces-c.a
          cp -r libs/* output/lib/
      - name: libMVRGdtf - wasm
        shell: bash
        working-directory: libMvrGdtf
        run: |
          cp parser.js libMVRgdtf/output/parser.js 
          cd libMVRgdtf/output 
          node parser.js 
          emcc -lembind -o main.js main.cpp --emit-tsd main.d.ts
      # - name: libMVRGdtf - wasm
      #   shell: bash
      #   working-directory: libMvrGdtf/libMVRgdtf/output/lib
      #   run: |
      #     emcc -lembind -o library.js --emit-tsd interface.d.ts -Wl,--whole-archive libMvrGdtf.a -Wl,--whole-archive libxerces-c.a -Wl,--no-whole-archive -s LINKABLE=1 -s EXPORT_ALL=1
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            libMvrGdtf/libMVRgdtf/output
